# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ricardo/Desktop/ROSS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ricardo/Desktop/ROSS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd /home/ricardo/Desktop/ROSS && $(CMAKE_COMMAND) -E cmake_progress_start /home/ricardo/Desktop/ROSS/CMakeFiles /home/ricardo/Desktop/ROSS/models/ispd-exa-engine-ross//CMakeFiles/progress.marks
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 models/ispd-exa-engine-ross/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ricardo/Desktop/ROSS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 models/ispd-exa-engine-ross/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 models/ispd-exa-engine-ross/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 models/ispd-exa-engine-ross/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/ricardo/Desktop/ROSS && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/rule:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/rule
.PHONY : models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/rule

# Convenience name for target.
ispd: models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/rule
.PHONY : ispd

# fast build rule for target.
ispd/fast:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build
.PHONY : ispd/fast

# Convenience name for target.
models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/rule:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/rule
.PHONY : models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/rule

# Convenience name for target.
ispd_test: models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/rule
.PHONY : ispd_test

# fast build rule for target.
ispd_test/fast:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build
.PHONY : ispd_test/fast

src/builder/builder.o: src/builder/builder.c.o
.PHONY : src/builder/builder.o

# target to build an object file
src/builder/builder.c.o:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/builder/builder.c.o
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/builder/builder.c.o
.PHONY : src/builder/builder.c.o

src/builder/builder.i: src/builder/builder.c.i
.PHONY : src/builder/builder.i

# target to preprocess a source file
src/builder/builder.c.i:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/builder/builder.c.i
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/builder/builder.c.i
.PHONY : src/builder/builder.c.i

src/builder/builder.s: src/builder/builder.c.s
.PHONY : src/builder/builder.s

# target to generate assembly for a file
src/builder/builder.c.s:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/builder/builder.c.s
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/builder/builder.c.s
.PHONY : src/builder/builder.c.s

src/log.o: src/log.c.o
.PHONY : src/log.o

# target to build an object file
src/log.c.o:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/log.c.o
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/log.c.o
.PHONY : src/log.c.o

src/log.i: src/log.c.i
.PHONY : src/log.i

# target to preprocess a source file
src/log.c.i:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/log.c.i
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/log.c.i
.PHONY : src/log.c.i

src/log.s: src/log.c.s
.PHONY : src/log.s

# target to generate assembly for a file
src/log.c.s:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/log.c.s
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/log.c.s
.PHONY : src/log.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/main.c.o
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/main.c.i
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/main.c.s
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/main.c.s
.PHONY : src/main.c.s

src/routing_table.o: src/routing_table.c.o
.PHONY : src/routing_table.o

# target to build an object file
src/routing_table.c.o:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/routing_table.c.o
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/routing_table.c.o
.PHONY : src/routing_table.c.o

src/routing_table.i: src/routing_table.c.i
.PHONY : src/routing_table.i

# target to preprocess a source file
src/routing_table.c.i:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/routing_table.c.i
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/routing_table.c.i
.PHONY : src/routing_table.c.i

src/routing_table.s: src/routing_table.c.s
.PHONY : src/routing_table.s

# target to generate assembly for a file
src/routing_table.c.s:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/routing_table.c.s
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/routing_table.c.s
.PHONY : src/routing_table.c.s

src/services/dummy.o: src/services/dummy.c.o
.PHONY : src/services/dummy.o

# target to build an object file
src/services/dummy.c.o:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/services/dummy.c.o
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/services/dummy.c.o
.PHONY : src/services/dummy.c.o

src/services/dummy.i: src/services/dummy.c.i
.PHONY : src/services/dummy.i

# target to preprocess a source file
src/services/dummy.c.i:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/services/dummy.c.i
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/services/dummy.c.i
.PHONY : src/services/dummy.c.i

src/services/dummy.s: src/services/dummy.c.s
.PHONY : src/services/dummy.s

# target to generate assembly for a file
src/services/dummy.c.s:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/services/dummy.c.s
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/services/dummy.c.s
.PHONY : src/services/dummy.c.s

src/services/link.o: src/services/link.c.o
.PHONY : src/services/link.o

# target to build an object file
src/services/link.c.o:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/services/link.c.o
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/services/link.c.o
.PHONY : src/services/link.c.o

src/services/link.i: src/services/link.c.i
.PHONY : src/services/link.i

# target to preprocess a source file
src/services/link.c.i:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/services/link.c.i
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/services/link.c.i
.PHONY : src/services/link.c.i

src/services/link.s: src/services/link.c.s
.PHONY : src/services/link.s

# target to generate assembly for a file
src/services/link.c.s:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/services/link.c.s
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/services/link.c.s
.PHONY : src/services/link.c.s

src/services/machine.o: src/services/machine.c.o
.PHONY : src/services/machine.o

# target to build an object file
src/services/machine.c.o:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/services/machine.c.o
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/services/machine.c.o
.PHONY : src/services/machine.c.o

src/services/machine.i: src/services/machine.c.i
.PHONY : src/services/machine.i

# target to preprocess a source file
src/services/machine.c.i:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/services/machine.c.i
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/services/machine.c.i
.PHONY : src/services/machine.c.i

src/services/machine.s: src/services/machine.c.s
.PHONY : src/services/machine.s

# target to generate assembly for a file
src/services/machine.c.s:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/services/machine.c.s
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/services/machine.c.s
.PHONY : src/services/machine.c.s

src/services/master.o: src/services/master.c.o
.PHONY : src/services/master.o

# target to build an object file
src/services/master.c.o:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/services/master.c.o
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/services/master.c.o
.PHONY : src/services/master.c.o

src/services/master.i: src/services/master.c.i
.PHONY : src/services/master.i

# target to preprocess a source file
src/services/master.c.i:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/services/master.c.i
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/services/master.c.i
.PHONY : src/services/master.c.i

src/services/master.s: src/services/master.c.s
.PHONY : src/services/master.s

# target to generate assembly for a file
src/services/master.c.s:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/services/master.c.s
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/services/master.c.s
.PHONY : src/services/master.c.s

src/workload/workload.o: src/workload/workload.c.o
.PHONY : src/workload/workload.o

# target to build an object file
src/workload/workload.c.o:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/workload/workload.c.o
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/workload/workload.c.o
.PHONY : src/workload/workload.c.o

src/workload/workload.i: src/workload/workload.c.i
.PHONY : src/workload/workload.i

# target to preprocess a source file
src/workload/workload.c.i:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/workload/workload.c.i
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/workload/workload.c.i
.PHONY : src/workload/workload.c.i

src/workload/workload.s: src/workload/workload.c.s
.PHONY : src/workload/workload.s

# target to generate assembly for a file
src/workload/workload.c.s:
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd.dir/src/workload/workload.c.s
	cd /home/ricardo/Desktop/ROSS && $(MAKE) $(MAKESILENT) -f models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/build.make models/ispd-exa-engine-ross/CMakeFiles/ispd_test.dir/src/workload/workload.c.s
.PHONY : src/workload/workload.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... ispd"
	@echo "... ispd_test"
	@echo "... src/builder/builder.o"
	@echo "... src/builder/builder.i"
	@echo "... src/builder/builder.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/routing_table.o"
	@echo "... src/routing_table.i"
	@echo "... src/routing_table.s"
	@echo "... src/services/dummy.o"
	@echo "... src/services/dummy.i"
	@echo "... src/services/dummy.s"
	@echo "... src/services/link.o"
	@echo "... src/services/link.i"
	@echo "... src/services/link.s"
	@echo "... src/services/machine.o"
	@echo "... src/services/machine.i"
	@echo "... src/services/machine.s"
	@echo "... src/services/master.o"
	@echo "... src/services/master.i"
	@echo "... src/services/master.s"
	@echo "... src/workload/workload.o"
	@echo "... src/workload/workload.i"
	@echo "... src/workload/workload.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/ricardo/Desktop/ROSS && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

